# Mathematical modelling

\vspace{-1cm}

\pagenumbering{gobble}

Maths is used to make sense of the world around us, and help us to make decisions, in our personal lives and in the worlds of business, politics, science, and so on. This could involve, for example:

\begin{itemize}[leftmargin=2.3cm]
    \item Creating and solving equations.
    \item Plotting graphs.
    \item Making calculations.
    \item Using computer software.
\end{itemize}

Each of these things could be thought of as creating a **mathematical model**. This chapter will introduce and explore a range of different kinds of model that may be useful, and when they may be encountered in the real world.

\begin{center}
    \begin{tcolorbox}[title=Quote,center,colback=DarkOrchid!5,colframe=DarkOrchid,width=10cm]
        \centering
        \textit{``All models are wrong, but some are useful.''}\\[0.2em]
        George Box, Statistician
    \end{tcolorbox}
\end{center}

The above quote highlights that mathematical models don't always need to be able to produce `the *right* answer', and in many situations such a thing is not even possible. Instead, the goal is often a simply a *useful* answer. Since we are entering a world of often *not knowing the true answer*, it is helpful to be learn some related vocabulary:

\begin{itemize}[leftmargin=2.3cm]
    \item \textbf{Accuracy} relates to how much a measurement or process leads towards the \textit{true value}.
    \item \textbf{Precision} relates to how close repeated measurements or processes are to \textit{each other}.
\end{itemize}

The results of four different archers aiming for the centre of a target should help illustrate the difference:

\begin{center}  
    \begin{tikzpicture}
        \draw[thick,fill=Cyan] (-7.5,0) circle (1.5cm);
        \draw[thick,fill=WildStrawberry] (-7.5,0) circle (1cm);
        \draw[thick,fill=Goldenrod] (-7.5,0) circle (0.5cm);
        \draw[thick,fill=Cyan] (-2.5,0) circle (1.5cm);
        \draw[thick,fill=WildStrawberry] (-2.5,0) circle (1cm);
        \draw[thick,fill=Goldenrod] (-2.5,0) circle (0.5cm);
        \draw[thick,fill=Cyan] (2.5,0) circle (1.5cm);
        \draw[thick,fill=WildStrawberry] (2.5,0) circle (1cm);
        \draw[thick,fill=Goldenrod] (2.5,0) circle (0.5cm);
        \draw[thick,fill=Cyan] (7.5,0) circle (1.5cm);
        \draw[thick,fill=WildStrawberry] (7.5,0) circle (1cm);
        \draw[thick,fill=Goldenrod] (7.5,0) circle (0.5cm);
        \node[left] at (-6.5,-2) {Accurate\;\textcolor{Green}{\cmark}};
        \node[left] at (-6.5,-2.7) {Precise\;\textcolor{Green}{\cmark}};
        \node[left] at (-1.5,-2) {Accurate\;\textcolor{Red}{\xmark}};
        \node[left] at (-1.5,-2.7) {Precise\;\textcolor{Green}{\cmark}};
        \node[left] at (3.5,-2) {Accurate\;\textcolor{Green}{\cmark}};
        \node[left] at (3.5,-2.7) {Precise\;\textcolor{Red}{\xmark}};
        \node[left] at (8.5,-2) {Accurate\;\textcolor{Red}{\xmark}};
        \node[left] at (8.5,-2.7) {Precise\;\textcolor{Red}{\xmark}};
        \draw[fill=black] (-7.4,0.2) circle (0.05);
        \draw[fill=black] (-7.7,-0.1) circle (0.05);
        \draw[fill=black] (-7.6,0.1) circle (0.05);
        \draw[fill=black] (-7.5,-0.3) circle (0.05);
        \draw[fill=black] (-7.4,0) circle (0.05);
        \draw[fill=black] (-1.1,-1.2) circle (0.05);
        \draw[fill=black] (-1.2,-1.0) circle (0.05);
        \draw[fill=black] (-1.3,-0.7) circle (0.05);
        \draw[fill=black] (-1.4,-0.9) circle (0.05);
        \draw[fill=black] (-1.5,-1.3) circle (0.05);
        \draw[fill=black] (3.6,0.3) circle (0.05);
        \draw[fill=black] (2.3,0.2) circle (0.05);
        \draw[fill=black] (1.8,-0.7) circle (0.05);
        \draw[fill=black] (3.1,-0.3) circle (0.05);
        \draw[fill=black] (2.0,0.6) circle (0.05);
        \draw[fill=black] (8.9,1.5) circle (0.05);
        \draw[fill=black] (9.0,1.1) circle (0.05);
        \draw[fill=black] (6.7,1.5) circle (0.05);
        \draw[fill=black] (8.1,0.6) circle (0.05);
        \draw[fill=black] (8.9,0.1) circle (0.05);
    \end{tikzpicture}
\end{center}

\pagebreak

## Systematic Estimation

The 20th century physicist Enrico Fermi was known for performing 'back of an envelope' calculations which often gave surprisingly reliable and *accurate* results. Calculations of this type are therefore sometimes called \textit{`Fermi estimates'}. The goal of these *systematic estimates* is to quickly get a sense of the *scale* of numerical answers to complex or even impossible questions such as:

\begin{center}
    \begin{tcolorbox}[title=Questions,center,colback=Aquamarine!5,colframe=Aquamarine,width=16cm]
        \begin{itemize}
            \item \textit{How many times might a teacher take a class register in their career?}
            \item \textit{How much on average does a large supermarket spend on staff wages each week?}
            \item \textit{How many miles are driven by cars on Scottish roads in a month?}
        \end{itemize}
    \end{tcolorbox}
\end{center}

These calculations might involve using a mixture of *approximated*, *estimated* and *exact* numbers. For example:

\begin{itemize}[leftmargin=2.3cm]
    \item There are \textbf{exactly} 60 seconds in one minute.
    \item There are \textbf{approximately} 30 days on average in a month.
    \item We might \textbf{estimate} the mass of a typical family car to be 1000 kilograms.
\end{itemize}

It is important to communicate clearly any **assumptions** made in reaching your answer, such as the *estimation* above.

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=NavyBlue]
\textbf{Problem:}

A secondary school in a city centre in Scotland has approximately 800 pupils.\\ Some buy their lunch in the dining hall and some buy their lunch from shops or bring their lunch from home.\\ Estimate the total amount spent on lunches in the school's dining hall per month.

\tcblower
\textbf{Solution:}

Assume that:

\begin{itemize}[itemsep=0pt]
    \item Half of the pupils in the school buy their lunch from the dining hall.
    \item On average £4 is spent on lunch each day by those pupils.
\end{itemize}

\[\text{400}\times \text{4} \times \text{20}=\text{32000}\approx \text{£30,000}\]

\end{tcolorbox}

You may have estimated a different proportion of pupils that use the dining hall, and a different average spend. This is okay, within reason. It is expected your final answer will vary based on your estimates of the different *variables*.

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=NavyBlue]
\textbf{Problem:}

Estimate the total volume of water that a typical person drinks during their childhood.

\tcblower
\textbf{Solution:}

Assume that:

\begin{itemize}[itemsep=0pt]
    \item `Childhood' lasts 18 years (from 0 to 18).
    \item On average a child might drink 1 litre of water a day.
\end{itemize}

\[\text{1}\times \text{365} \times \text{18}=\text{6570}\approx \text{6600 litres}\]

\end{tcolorbox}

\pagebreak

[]{#ex11q}

#### [Exercise 1.1](#ex11a) {-}

\newpage

## Modelling Relationships using Graphs

We may wish to explore the *relationships* between two or more variables, such as when considering:

\begin{center}
    \begin{tcolorbox}[title=Questions,center,colback=Aquamarine!5,colframe=Aquamarine,width=16cm]
        \begin{itemize}
            \item How will the \textbf{money} in my savings account grow over \underline{time} if I make regular payments?
            \item What might a car's \textbf{braking distance} by when travelling at different \underline{speeds}?
            \item How might the \underline{distance} travelled in a taxi be related to the \textbf{fare}?
        \end{itemize}
    \end{tcolorbox}
\end{center}

We should aim to identify where possible for any relationship:

\begin{itemize}[leftmargin=2.3cm]
    \item The \underline{independent} variable - commonly either \textit{time} or one which we \underline{control}.
    \item The \textbf{depdendent} variable - which changes in \textbf{response} to the other.
\end{itemize}

Creating graph of a possible model is a good starting point in understanding any relationship. The *independent* variable should be placed along the (horizontal) $x$-axis and the *response* variable placed on the (vertical) $y$-axis.

You may have to *sketch* a possible graph of a relationship, or *select from a choice of graphs*, giving an explanation.

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=NavyBlue]

\textbf{Problem:}

Bob pours water into an empty cup at a constant rate.\\ The interior of the cup is in the shape of a hemisphere, as shown below.
\begin{multicols}{2}
\begin{center}
\begin{tikzpicture}[scale=1.1]

\tikzset{xshift={mod(1,2)*3cm}, yshift=-floor(1/2)*3cm}
\colorlet{cup}{Purple!75!black}

% Saucer
\begin{scope}[shift={(0,-1-1/16)}]
    \fill [black!87.5, path fading=fade out] 
      (0,-2/8) ellipse [x radius=6/4, y radius=3/4];
    \fill [cup, postaction={left color=black, right color=white, opacity=1/3}] 
      (0,0) ++(180:5/4) arc (180:360:5/4 and 5/8+1/16);
    \fill [cup, postaction={left color=black!50, right color=white, opacity=1/3}] 
      (0,0) ellipse [x radius=5/4, y radius=5/8];
    \fill [cup, postaction={left color=white, right color=black, opacity=1/3}]
      (0,1/16) ellipse [x radius=5/4/2, y radius=5/8/2];
    \fill [cup, postaction={left color=black, right color=white, opacity=1/3}] 
      (0,0) ellipse [x radius=5/4/2-1/16, y radius=5/8/2-1/16];
\end{scope} 

% Handle
\begin{scope}[shift=(10:7/8), rotate=-30, yslant=1/2, xslant=-1/8]
  \fill [cup, postaction={top color=black, bottom color=white, opacity=1/3}] 
    (0,0) arc (130:-100:3/8 and 1/2) -- ++(0,1/4) arc (-100:130:1/8 and 1/4) -- cycle;
  \fill [cup, postaction={top color=white, bottom color=black, opacity=1/3}] 
    (0,0) arc (130:-100:3/8 and 1/2) -- ++(0,1/32) arc (-100:130:1/4 and 1/3) -- cycle;
\end{scope}

% Cup
\fill [cup!25!black, path fading=fade out] 
    (0,-1-1/16) ellipse [x radius=3/4, y radius=1/3];
\fill [cup, postaction={left color=black, right color=white, opacity=1/3/2},
  postaction={bottom color=black, top color=white, opacity=1/3/2}] 
    (-1,0) arc (180:360:1 and 5/4);
\fill [cup, postaction={left color=white, right color=black, opacity=1/3}] 
  (0,0) ellipse [x radius=1, y radius=1/2];
\fill [cup, postaction={left color=black, right color=white, opacity=1/3/2},
  postaction={bottom color=black, top color=white, opacity=1/3/2}] 
    (0,0) ellipse [x radius=1-1/16, y radius=1/2-1/16];

% Coffee
\begin{scope}
\clip ellipse [x radius=1-1/16, y radius=1/2-1/16];
\fill [MidnightBlue!25!white] 
  (0,-1/4) ellipse [x radius=3/4, y radius=3/8];
\fill [MidnightBlue!50!white, path fading=fade out] 
  (0,-1/4) ellipse [x radius=3/4, y radius=3/8];
\end{scope}

\end{tikzpicture}
\end{center}

\begin{center}
\begin{tikzpicture}[scale=0.7]
	% Draw a shaded ball, but clip so only the lower half shows.
	% The arc in the clipping region is the foreground part of the equator
	\begin{scope}
	    \clip(-3,-3) -- (-3,0) -- (-2,0) arc (180:360:2cm and 0.6cm) -- (3,0) -- (3,-3) -- (-3,-3);
		\shade[ball color=MidnightBlue!60!white, opacity=0.70] (0,0) circle (2cm);
	\end{scope}

	% Draw the disc on top of the hemisphere.
    \shade[shading=radial, inner color=MidnightBlue!40!white, outer color=MidnightBlue!60!white, opacity=0.70] (2,0) arc (0:360:2cm and 0.6cm); 
	
	% Outline the disk in black
    \draw (2,0) arc (0:360:2cm and 0.6cm);

	% Outline the hemisphere in black
    \draw (-2,0) arc (180:360:2cm and 2cm);
    \draw[stealth-stealth] (3.4,-2) -- (3.4,0);
    \node[right] at (3.4,-1) {depth};
\end{tikzpicture}
\end{center}


\end{multicols}

State which of graphs A, B or C below might be best suited to model the relationship between the time since Bob began pouring the water and the depth of water in the cup, explaining your answer.

\begin{multicols}{3}

\begin{tikzpicture}
    \node[above] at (2,4) {Graph A};
    \draw[step=0.4cm,black!30] (0,0) grid (4,4);
    \draw[-stealth] (0,0) -- (0,4.2);
    \draw[-stealth] (0,0) -- (4.2,0);
    \node[below] at (2,0) {time (seconds)};
    \node[above,rotate=90] at (0,2) {depth (cm)};
    \node[below left] at (0,0) {0};
    \draw[very thick,MidnightBlue!80!white,domain=0:4,smooth,samples=100] plot (\x,{0.225*(\x)^2});
    \node[below] at (4,0) {4};
    \node[left] at (0,3.6) {6};
\end{tikzpicture}

\begin{tikzpicture}
    \node[above] at (2,4) {Graph B};
    \draw[step=0.4cm,black!30] (0,0) grid (4,4);
    \draw[-stealth] (0,0) -- (0,4.2);
    \draw[-stealth] (0,0) -- (4.2,0);
    \node[below] at (2,0) {time (seconds)};
    \node[above,rotate=90] at (0,2) {depth (cm)};
    \node[below left] at (0,0) {0};
    \draw[very thick,MidnightBlue!80!white,domain=0:4,smooth,samples=100] plot (\x,{0.9*\x});
    \node[below] at (4,0) {4};
    \node[left] at (0,3.6) {6};
\end{tikzpicture}

\begin{tikzpicture}
    \node[above] at (2,4) {Graph C};
    \draw[step=0.4cm,black!30] (0,0) grid (4,4);
    \draw[-stealth] (0,0) -- (0,4.2);
    \draw[-stealth] (0,0) -- (4.2,0);
    \node[below] at (2,0) {time (seconds)};
    \node[above,rotate=90] at (0,2) {depth (cm)};
    \node[below left] at (0,0) {0};
    \draw[very thick,MidnightBlue!80!white,domain=0:4,smooth,samples=100] plot (\x,{1.8*(\x)^0.5});
    \node[below] at (4,0) {4};
    \node[left] at (0,3.6) {6};
\end{tikzpicture}

\end{multicols}

\tcblower
\textbf{Solution:}

Graph C, since the depth will increase more quickly at the start, then slow down towards the end.

\end{tcolorbox}

\pagebreak

[]{#ex12q}

#### [Exercise 1.2](#ex12a) {-}

\newpage

## Linear Relationships

Some types of relationship are commonly encountered, and the rest of this chapter will study these in more detail. One of the simplest relationships between two variables is a *linear relationship*, which on a graph is a **straight line**. A linear relationship is defined by a **constant rate of change**, which can be calculated as the *gradient* of the graph. This tells us the amount of change in the response variable for each positive unit change in the independent variable.

For example, consider the linear relationship between the price of a taxi ride (£$p$) and the distance travelled ($d$ km).

\begin{multicols}{2}

\begin{center}
    \begin{tikzpicture}
        \draw[black!20,step=0.25cm] (0,0) grid (5,4);
        \draw[-stealth] (0,0) -- (5.15,0) node[right] {$d$};
        \draw[-stealth] (0,0) -- (0,4.15) node[above] {$p$};
        \node[below] at (2.5,-0.5) {distance (km)};
        \node[above,rotate=90] at (-0.5,2) {price (£)};
        \foreach \x in {0,10,20,30,50}{
        \node[below] at (0.1*\x,0) {\x};
}
        \node[RoyalBlue,below] at (4,0) {40};
        \foreach \x in {0,5,...,50}{
        \draw (0.1*\x,0) -- (0.1*\x,-0.1);
}
        \foreach \y in {0,5,...,40}{
        \draw (0,0.1*\y) -- (-0.1,0.1*\y);
}
        \foreach \y in {0,20,...,80}{
        \node[left] at (0,0.05*\y) {\y};
}
        \draw[very thick,Plum] (0,0.25) -- (5,4) node[above] {$p=\text{5}+\text{1.5}d$};
        \fill[WildStrawberry] (0,0.25) circle (0.05);
        \fill[Emerald] (2,1.75) circle (0.05);
        \fill[Emerald] (3,2.5) circle (0.05);
        \fill[RoyalBlue] (4,3.25) circle (0.05);
        \draw[thick,dashed,Emerald] (2,1.75) -- (3,1.75) -- (3,2.5);
        \node[below,Emerald] at (2.5,1.75) {10 km};
        \node[right,Emerald] at (3,2.125) {£15};
        \draw[thick,WildStrawberry,stealth-] (-0.1,0.3) -- (-0.5,0.5) node[left] {£5};
        \draw[thick,RoyalBlue,stealth-] (-0.1,3.3) -- (-0.5,3.5) node[left] {£65};
        \draw[thick,dashed,RoyalBlue] (4,0) -- (4,3.25) -- (0,3.25);
    \end{tikzpicture}
\end{center}


The \textcolor{Emerald}{\textbf{rate of change}} is $\frac{\text{15}}{\text{10}}=£\text{1.50}\text{ per km}$, so\\ each extra kilometre increases the price by £1.50.

\vspace{0.5cm}

The graph's \textcolor{WildStrawberry}{\textbf{starting value}}, for a distance of 0 kilometres is £5. (The taxi company's `base charge').

\vspace{0.5cm}

Note that both the \textit{starting value} and the \textit{rate of change} can be observed from the relationship's \textcolor{Plum}{\textbf{equation}}:

\begin{center}
\framebox{\textcolor{Plum}{$\textbf{price}=\text{5}+\text{1.5}\times\textbf{distance}$}}
\end{center}

\vfill\null

\end{multicols}

\vspace{-0.8cm}

For any equation of the form $y=a+bx$ describing a linear relationship between $x$ and $y$, the value of $a$ tells us the *starting value* of $y$ (when $x=\text{0}$), and the value of $b$ tells us how much $y$ changes for each `step' in the $x$ direction.

The \textcolor{RoyalBlue}{\textit{dashed line}} shows how the graph can be used to \textcolor{RoyalBlue}{\textbf{predict}} a price of £65 for a distance of 40 kilometres.

The equation can also be used:

\vspace{-0.4cm}

\[\text{price}=\text{5}+\text{1.5}\times\text{40}=65\]

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=NavyBlue]
\textbf{Problem:}

A candle with a height of 20 centimetres is lit. It loses 4 centimetres of height per hour as it burns.

\begin{enumerate}[(a)]
    \item Write down an equation connecting the candle's height and its burn time.
    \item State the units used to measure the rate of change.
    \item State which is the independent variable and which is the response variable.
    \item Use the equation to calculate the height of the candle after 90 \textbf{minutes} spent burning.
    \item Draw a graph to show the relationship.
\end{enumerate}

\tcblower
\textbf{Solution:}

\begin{multicols}{2}

\begin{enumerate}[(a)]
    \item $\text{height}=\text{20}-\text{4}\times\text{time}$
    \item Centimetres per hour.
    \item The independent variable is time.\\The response variable is height.
    \item $\text{height}=\text{20}-\text{4}\times\text{1.5}=\text{14 cm}$
\end{enumerate}

\vfill\null
\columnbreak

\begin{tikzpicture}
    \draw[black!20,step=0.25cm] (0,0) grid (6,2.6);
    \draw[-stealth] (0,0) -- (6.2,0);
    \draw[-stealth] (0,0) -- (0,2.7);
    \foreach \x in {0,1,...,6}{
    \draw (\x,0) node[below] {\x}-- (\x,-0.1);
}
    \node[below] at (3,-0.5) {burn time (hours)};
    \foreach \y in {0,10,20}{
    \node[left] at (0,0.1*\y) {\y};
}
    \foreach \y in {0,0.5,...,2}{
    \draw (0,\y) -- (-0.1,\y);
}
    \draw[very thick,RoyalBlue] (0,2) -- (5,0);
    \node[above,rotate=90] at (-0.8,1.2) {height (cm)};
    \node at (-1.3,2.7) {(e)};
\end{tikzpicture}

\end{multicols}

\end{tcolorbox}

\pagebreak

[]{#ex13q}

#### [Exercise 1.3](#ex13a) {-}

\newpage

## Quadratic Relationships

*Quadratic relationships* occur in a wide range of situations, from the shape of satellite dishes to the design of certain kinds of bridges. One of the most common applications of a quadratic equation is when considering any object acting under gravity, such as a ball thrown through the air.

\begin{multicols}{2}

\begin{center}
    \begin{tikzpicture}
        \draw[thin,samples=100,smooth,domain=0.3:6.7,dashed,Fuchsia] plot (\x,{-0.2*(\x)^2+1.4*(\x)+0.85});
        \shade [ball color=BrickRed] (6.5,1.5) circle (0.15);
        \draw[very thick,Fuchsia,samples=100,smooth,domain=1:6,-stealth] plot (\x,{-0.2*(\x)^2+1.4*(\x)+0.85});
        \draw[very thick,-stealth] (3.5,2) -- (3.5,1) node[below] {gravity};
    \end{tikzpicture}
\end{center}


The \textcolor{Fuchsia}{\textbf{shape}} of the graph produced is called a \textcolor{Fuchsia}{\textbf{parabola}}.

The 'flipped' version is also a parabola, and the squared term's \textit{sign} tells us if it is a \textcolor{ForestGreen}{\textbf{positive}} or \textcolor{BrickRed}{\textbf{negative}} parabola.

\vspace{-0.3cm}

\begin{center}
    \begin{tikzpicture}
        \draw[very thick,ForestGreen,samples=100,smooth,domain=0.5:3] plot (\x,{(\x)^2-3.5*(\x)+3.5625});
        \draw[very thick,BrickRed,samples=100,smooth,domain=4:6.5] plot (\x,{-(\x)^2+10.5*(\x)-25.5625});
        \node[left] at (0.5,1) {$h=$\textcolor{ForestGreen}{$t^2$}};
        \node[right] at (6.5,1) {$h=$\textcolor{BrickRed}{$-t^2$}};
        \draw[stealth-] (1.75,0.6) -- (1.75,1) node[above] {minimum};
        \draw[stealth-] (5.25,1.9) -- (5.25,1.5) node[below] {maximum};
    \end{tikzpicture}
\end{center}

\end{multicols}

\vspace{-0.2cm}

The typical feature of a parabola is that it either *falls then rises* or *rises then falls* **symmetrically**, with a *turning point* in the middle - either a *minimum turning point* or a *maximum turning point* respectively. Studying *quadratic behaviour* in detail forms parts of the National 5 Mathematics and Higher Mathematics courses. Key skills required for the Higher Applications course include:

\begin{itemize}[leftmargin=2cm]
    \item \textbf{Recognising} a quadratic relationship through inspecting a graph.
    \item Using an \textbf{equation} to find the `output' (response variable) for a given `input' (independent variable). 
    \item Using a \textbf{graph} to predict the `output' (response variable) for a given `input' (independent variable). 
\end{itemize}

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=NavyBlue]
\textbf{Problem:}

The height ($h$ metres) of a ball thrown up at a speed of 15 metres per second from 2 metres above the ground $t$ seconds after it is thrown is given by the equation below. Calculate the height after three seconds.

\vspace{-0.2cm}

\[h=-\text{4.9}t^{\text{2}}+\text{15}t+\text{2}\]

\tcblower
\textbf{Solution:}

\vspace{-0.2cm}

\[h=-\text{4.9}\times \text{3}^2 + \text{15}\times\text{3}+\text{2}=\text{2.9 metres}\]

\end{tcolorbox}

\begin{tcolorbox}[title=Example,colback=RoyalBlue!1!,colframe=NavyBlue,sidebyside]
\textbf{Problem:}

The graph below shows the 

\vspace{-0.2cm}

\[h=-\text{4.9}t^{\text{2}}+\text{15}t+\text{2}\]

\tcblower
\textbf{Solution:}

\vspace{-0.2cm}

\[h=-\text{4.9}\times \text{3}^2 + \text{15}\times\text{3}+\text{2}=\text{2.9 metres}\]

\end{tcolorbox}

\newpage

[]{#ex14q}

#### [Exercise 1.4](#ex14a) {-}

\newpage

## Exponential Relationships

\newpage

[]{#ex15q}

#### [Exercise 1.5](#ex15a) {-}

\newpage

[]{#re1q}

## [Review Exercise](#re1a) {-}
